<ul class="ChkBoxList"> 
    <li> <input class="headings" type="checkbox" name="headinds" value="Bike"><b>Week 1 - Science-writing</b></li><li><input class="selectedId" id="oYiOOqhMEeWImQpCNZFpPQ" type="checkbox" name="checkbox[]" value="Welcome words:oYiOOqhMEeWImQpCNZFpPQ">Welcome words.mp4</li><li><input class="selectedId" id="gfkECq3uEeWxaw7Jay15BQ" type="checkbox" name="checkbox[]" value="Writing in English:gfkECq3uEeWxaw7Jay15BQ">Writing in English.mp4</li>
    <li><input class="selectedId" id="3ULDvK3uEeW1-RKql4-XpQ" type="checkbox" name="checkbox[]" value="Anglo-American Rhetorical Traditions:3ULDvK3uEeW1-RKql4-XpQ">Anglo-American Rhetorical Traditions.mp4</li><li><input class="selectedId" id="K8E3o63vEeW1-RKql4-XpQ" type="checkbox" name="checkbox[]" value="Golden Rules of Scientific Writing:K8E3o63vEeW1-RKql4-XpQ">Golden Rules of Scientific Writing.mp4</li><li><input class="selectedId" id="IZxZc633EeW1-RKql4-XpQ" type="checkbox" name="checkbox[]" value="Clarity, Precision, and Accuracy:IZxZc633EeW1-RKql4-XpQ">Clarity, Precision, and Accuracy.mp4</li><li><input class="selectedId" id="lcapWK33EeWRRQpQejjiSw" type="checkbox" name="checkbox[]" value="Hedging:lcapWK33EeWRRQpQejjiSw">Hedging.mp4</li><li><input class="selectedId" id="WOFLnq35EeW3mhLW1_Ertw" type="checkbox" name="checkbox[]" value="Fuzzy and Smothered Words:WOFLnq35EeW3mhLW1_Ertw">Fuzzy and Smothered Words.mp4</li><li><input class="selectedId" id="cwJRC64mEeWDwQ7PSvPrHw" type="checkbox" name="checkbox[]" value="Function and Structure Words:cwJRC64mEeWDwQ7PSvPrHw">Function and Structure Words.mp4</li><li><input class="selectedId" id="jmMipq4mEeW1-RKql4-XpQ" type="checkbox" name="checkbox[]" value="I and We in Scientific Writing:jmMipq4mEeW1-RKql4-XpQ">I and We in Scientific Writing.mp4</li><li><input class="selectedId" id="ntPQhq4mEeWImQpCNZFpPQ" type="checkbox" name="checkbox[]" value="Who, Which, … or What?:ntPQhq4mEeWImQpCNZFpPQ">Who, Which, … or What?.mp4</li>
    <ul class="ChkBoxList"><li> <input class="headings" type="checkbox" name="headinds" value="Bike"><b>Week 2 - The-challenge</b></li>
        <li><input class="selectedId" id="PG82TahmEeWVWxIHjj3fKQ" type="checkbox" name="checkbox[]" value="Wayward Modifiers:PG82TahmEeWVWxIHjj3fKQ">Wayward Modifiers.mp4</li>
        <li><input class="selectedId" id="Rjpi3qhmEeWVdAqQVb1YyQ" type="checkbox" name="checkbox[]" value="Hidden Negation:Rjpi3qhmEeWVdAqQVb1YyQ">Hidden Negation.mp4</li>
        <li><input class="selectedId" id="TCthpqhmEeWV-A6Oxpvjnw" type="checkbox" name="checkbox[]" value="Active vs. Passive:TCthpqhmEeWV-A6Oxpvjnw">Active vs. Passive.mp4</li>
        <li><input class="selectedId" id="xlBgRqh-EeWRRQpQejjiSw" type="checkbox" name="checkbox[]" value="Tenses in Scientific Writing:xlBgRqh-EeWRRQpQejjiSw">Tenses in Scientific Writing.mp4</li><li><input class="selectedId" id="1CMxeKh-EeWV-A6Oxpvjnw" type="checkbox" name="checkbox[]" value="Punctuation:1CMxeKh-EeWV-A6Oxpvjnw">Punctuation.mp4</li><li><input class="selectedId" id="24nhTqh-EeW3mhLW1_Ertw" type="checkbox" name="checkbox[]" value="A Unit of Composition:24nhTqh-EeW3mhLW1_Ertw">A Unit of Composition.mp4</li>
        <li><input class="selectedId" id="gCGxLaiAEeWVdAqQVb1YyQ" type="checkbox" name="checkbox[]" value="Anglo-American Style of Argumentation:gCGxLaiAEeWVdAqQVb1YyQ">Anglo-American Style of Argumentation.mp4</li><li><input class="selectedId" id="iKG_rKiAEeW1Wg5FY1MuFQ" type="checkbox" name="checkbox[]" value="Presenting Results or Telling a Story?:iKG_rKiAEeW1Wg5FY1MuFQ">Presenting Results or Telling a Story?.mp4</li><li><input class="selectedId" id="kEKRp6iAEeWyvg4disSh_Q" type="checkbox" name="checkbox[]" value="Journal Analysis:kEKRp6iAEeWyvg4disSh_Q">Journal Analysis.mp4</li>                                       
        <ul class="ChkBoxList"><li> <input class="headings" type="checkbox" name="headinds" value="Bike"><b>Week 3 - The-manuscript</b></li>
            <li><input class="selectedId" id="eibRqqiBEeWyxBK5kOJEJw" type="checkbox" name="checkbox[]" value="Manuscript Guidelines: Insider Knowledge:eibRqqiBEeWyxBK5kOJEJw">Manuscript Guidelines: Insider Knowledge.mp4</li><li><input class="selectedId" id="iIGYNqiBEeWGUgpgKqm2yQ" type="checkbox" name="checkbox[]" value="The IMRaD Format:iIGYNqiBEeWGUgpgKqm2yQ">The IMRaD Format.mp4</li><li><input class="selectedId" id="jrDYrqiBEeWxaw7Jay15BQ" type="checkbox" name="checkbox[]" value="Introduction:jrDYrqiBEeWxaw7Jay15BQ">Introduction.mp4</li>
            <li><input class="selectedId" id="GuKVgKiCEeWyxBK5kOJEJw" type="checkbox" name="checkbox[]" value="Materials and Methods:GuKVgKiCEeWyxBK5kOJEJw">Materials and Methods.mp4</li><li><input class="selectedId" id="IznmTKiCEeW1-RKql4-XpQ" type="checkbox" name="checkbox[]" value="Results:IznmTKiCEeW1-RKql4-XpQ">Results.mp4</li>
            <li><input class="selectedId" id="Kr1sNaiCEeWVWxIHjj3fKQ" type="checkbox" name="checkbox[]" value="Discussion:Kr1sNaiCEeWVWxIHjj3fKQ">Discussion.mp4</li><li><input class="selectedId" id="ASpOsKiDEeW24RJH5gkutw" type="checkbox" name="checkbox[]" value="Title, Abstract, and Keywords:ASpOsKiDEeW24RJH5gkutw">Title, Abstract, and Keywords.mp4</li><li><input class="selectedId" id="CndxEaiDEeWyvg4disSh_Q" type="checkbox" name="checkbox[]" value="Acknowledgments:CndxEaiDEeWyvg4disSh_Q">Acknowledgments.mp4</li>
            <li><input class="selectedId" id="EMJ2xKiDEeWVWxIHjj3fKQ" type="checkbox" name="checkbox[]" value="References:EMJ2xKiDEeWVWxIHjj3fKQ">References.mp4</li>                                       
            <ul class="ChkBoxList"><li> <input class="headings" type="checkbox" name="headinds" value="Bike"><b>Week 4 - Scientific-communication</b></li><li><input class="selectedId" id="Ag4B96iEEeWK-gr2JZre1Q" type="checkbox" name="checkbox[]" value="Submitting a Manuscript:Ag4B96iEEeWK-gr2JZre1Q">Submitting a Manuscript.mp4</li><li><input class="selectedId" id="CBvYZ6iEEeWyvg4disSh_Q" type="checkbox" name="checkbox[]" value="The Publishing Process:CBvYZ6iEEeWyvg4disSh_Q">The Publishing Process.mp4</li>
                <li><input class="selectedId" id="DvFDrqiEEeW1Wg5FY1MuFQ" type="checkbox" name="checkbox[]" value="Dealing with Editors:DvFDrqiEEeW1Wg5FY1MuFQ">Dealing with Editors.mp4</li>
                <li><input class="selectedId" id="3bOPjaiEEeWRRQpQejjiSw" type="checkbox" name="checkbox[]" value="Ethics:3bOPjaiEEeWRRQpQejjiSw">Ethics.mp4</li><li><input class="selectedId" id="6OqoM6iEEeW1Wg5FY1MuFQ" type="checkbox" name="checkbox[]" value="Self-promotion in social networks:6OqoM6iEEeW1Wg5FY1MuFQ">Self-promotion in social networks.mp4</li>
                <li><input class="selectedId" id="utwrB6hMEeW1-RKql4-XpQ" type="checkbox" name="checkbox[]" value="A Scientific-Communication Career:utwrB6hMEeW1-RKql4-XpQ">A Scientific-Communication Career.mp4</li>
            </ul>
        </ul>
    </ul>
</ul>